name: Check and Convert CRLF to LF

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-convert-line-endings:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This line grants write access to the GITHUB_TOKEN
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Find and Convert CRLF to LF
        run: |
          echo "Looking for files with CRLF line endings in the repository..."
          
          # Use find to locate all files (not just .json files) and handle filenames with spaces
          # The -print0 option and 'read -r -d $'\0' file' are crucial for handling special characters in file paths
          find . -type f -print0 | while IFS= read -r -d $'\0' file; do
            # Skip binary files to prevent issues
            if file -i "$file" | grep -q 'charset=binary'; then
              echo "Skipping binary file: $file"
              continue
            fi
            
            # Use sed to remove carriage return characters ('\r')
            # The -i flag modifies the file in place
            # 's/\r$//' removes a carriage return at the end of a line
            if grep -q $'\r' "$file"; then
              echo "Converting CRLF to LF in $file"
              sed -i 's/\r$//' "$file"
            fi
          done

      - name: Commit and Push Changes
        run: |
          # Check if any changes were made by the previous step
          if ! git diff-index --quiet HEAD; then
            echo "CRLF line endings were found and converted. Committing changes."
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Auto: Convert CRLF to LF line endings"
            git push
          else
            echo "No CRLF line endings were found or converted. No changes to push."
          fi
      
